spring:
  cloud:
    gateway:
      routes:
        - id: turing-user-aggregation-service
          uri: lb://turing-aggregation${unique-name:}-service/api/user-service/**
          predicates:
            - Path=/api/user-service/**
          filters:
            - name: TokenValidate
              args:
                blackPathPre:
                  - /api/user-service/passenger
                  - /api/user-service/query
                  - /api/user-service/logout
                  - /api/user-service/deletion

        - id: turing-ticket-aggregation-service
          uri: lb://turing-aggregation${unique-name:}-service/api/ticket-service/**
          predicates:
            - Path=/api/ticket-service/**
          filters:
            - name: TokenValidate
              args:
                blackPathPre:
                  - /api/ticket-service/ticket/purchase
                  - /api/ticket-service/ticket/pay/query
                  - /api/ticket-service/ticket/cancel

        - id: turing-pay-aggregation-service
          uri: lb://turing-aggregation${unique-name:}-service/api/pay-service/**
          predicates:
            - Path=/api/pay-service/**

        - id: turing-order-aggregation-service
          uri: lb://turing-aggregation${unique-name:}-service/api/order-service/**
          predicates:
            - Path=/api/order-service/**
          filters:
            - name: TokenValidate
              args:
                blackPathPre:
                  - /api/order-service/order/ticket/query
                  - /api/order-service/order/ticket/page
                  - /api/order-service/order/ticket/self/page
